on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-24.04, macos-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Configure and build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target quick_sort_random_pivot
          cmake --build build --target quick_sort
          cmake --build build --target quick_3way_sort
          cmake --build build --target counting_sort
          cmake --build build --target tim_sort

      - name: Install target
        run: |
          cd build && cmake --install .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}
          path:
            bin/*
          retention-days: 7
