on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-24.04, macos-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Configure and build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target quick_sort_random_pivot
          cmake --build build --target quick_sort
          cmake --build build --target quick_3way_sort
          cmake --build build --target counting_sort
          cmake --build build --target tim_sort

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}
          path:
            bin/*
          retention-days: 3

  execute:
    needs: build
    strategy:
      matrix:
        os: [ ubuntu-24.04, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}

      - name: Run executables counting_sort
        continue-on-error: true
        run: |
          chmod +x ./counting_sort 
          ./counting_sort  length linear
          ./counting_sort  length exponential
          ./counting_sort  max linear
          ./counting_sort  max exponential

      - name: Run executables quick_sort
        continue-on-error: true
        run: |
          chmod +x ./quick_sort
          ./quick_sort length linear
          ./quick_sort length exponential
          ./quick_sort max linear
          ./quick_sort max exponential

      - name: Run executables quick_3way_sort
        continue-on-error: true
        run: |
          chmod +x ./quick_3way_sort
          ./quick_3way_sort length linear
          ./quick_3way_sort length exponential
          ./quick_3way_sort max linear
          ./quick_3way_sort max exponential

      - name: Run executables quick_sort_random_pivot
        continue-on-error: true
        run: |
          chmod +x ./quick_sort_random_pivot
          ./quick_sort_random_pivot length linear
          ./quick_sort_random_pivot length exponential
          ./quick_sort_random_pivot max linear
          ./quick_sort_random_pivot max exponential

      - name: Run executables tim_sort
        continue-on-error: true
        run: |
          chmod +x ./tim_sort
          ./tim_sort length linear
          ./tim_sort length exponential
          ./tim_sort max linear
          ./tim_sort max exponential

      - name: Upload CSV artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-csv-${{ matrix.os }}
          path: '**/*.csv'
          retention-days: 7

  release:
    permissions:
      contents: write

    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Download artifacts ubuntu-24.04
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-ubuntu-24.04
          path: build-artifacts-ubuntu-24.04

      - name: Download artifacts macos-latest
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-macos-latest
          path: build-artifacts-macos-latest

      - name: Compress artifacts
        run: |
          tar -czf artifacts-ubuntu-24.04.tar.gz build-artifacts-ubuntu-24.04/*
          tar -czf artifacts-macos-latest.tar.gz build-artifacts-macos-latest/*

      - name: Create GitHub release
        if: ${{ github.event_name == 'push' }}
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            This is an automated release.
            Created by ${{ github.actor }} on date ${{ github.event.created_at }}.
          tag_name: auto/${{ steps.get_date.outputs.date }}-${{ github.sha }}
          files: |
            artifacts-ubuntu-24.04.tar.gz
            artifacts-macos-latest.tar.gz
